/**
 * SIM-TIRTA LESTARI - Config.gs
 * KPSPAM TIRTA LESTARI, Kalurahan Ngawu, Kapanewon Playen, Kabupaten Gunungkidul
 */

const CONFIG = {
  APP_NAME: 'SIM-TIRTA LESTARI',
  APP_VERSION: 'v1.0.0',
  TIMEZONE: 'Asia/Jakarta',
  LOCALE: 'id-ID',

  SHEETS: {
    SETTINGS: 'SETTINGS',
    USERS: 'USERS',
    CUSTOMERS: 'CUSTOMERS',
    CONNECTIONS: 'CONNECTIONS',
    METER_READINGS: 'METER_READINGS',
    TARIFFS: 'TARIFFS',
    BILLS: 'BILLS',
    PAYMENTS: 'PAYMENTS',
    RECEIPTS: 'RECEIPTS',
    ARREARS: 'ARREARS',
    CASH_IN: 'CASH_IN',
    CASH_OUT: 'CASH_OUT',
    BANK_LEDGER: 'BANK_LEDGER',
    ASSETS: 'ASSETS',
    MAINTENANCE: 'MAINTENANCE',
    COMPLAINTS: 'COMPLAINTS',
    COMPLAINT_HISTORY: 'COMPLAINT_HISTORY',
    ANNOUNCEMENTS: 'ANNOUNCEMENTS',
    PUBLIC_REPORTS: 'PUBLIC_REPORTS',
    AUDIT_LOG: 'AUDIT_LOG',
    BACKUP_LOG: 'BACKUP_LOG'
  },

  CACHE_TTL: {
    PUBLIC_DATA: 600,
    SETTINGS: 1800,
    TARIFFS: 1800
  },

  DRIVE_FOLDERS: {
    ROOT: 'SIM TIRTA LESTARI',
    RECEIPTS: 'KWITANSI',
    REPORTS: 'LAPORAN',
    COMPLAINTS: 'PENGADUAN',
    EXPENSES: 'BUKTI PENGELUARAN',
    BACKUP: 'BACKUP',
    LOGO: 'LOGO'
  }
};
